import {useEffect,useState} from 'react';
import {useSelector} from 'react-redux';
import axios from 'axios';
import {API_BASE_URL} from '@/config/apiConfig';
import {Button} from './ui/button';
import {Heart,MessageCircle,Trash2} from 'lucide-react';
import {toast} from 'sonner';
export default function CourseCommunity({courseId}) {
  const user=useSelector(s=>s.auth.user);const [data,setData]=useState(null);const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const base=`${API_BASE_URL}/api/v1/course`;const load=()=>axios.get(`${base}/social/${courseId}${user?'/mine':''}`,{withCredentials:true}).then(r=>{setData(r.data);setError('');}).catch(()=>setError('Community activity could not load.'));
  useEffect(()=>{load();},[courseId,user?._id]);
  const action=async(fn)=>{setBusy(true);try{await fn();await load();}catch(e){toast.error(e.response?.data?.message||'Could not save. Please try again.');}finally{setBusy(false);}};
  return <section className="mt-8 rounded-2xl border bg-card p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><MessageCircle size={20}/>Course community</h2>{error?<p role="alert" className="mt-4 text-sm">{error}<Button variant="link" onClick={load}>Retry</Button></p>:!data?<p className="mt-4 text-muted-foreground">Loading activity...</p>:<>{data.isDemo&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950 dark:text-amber-200">This is a synthetic demo course. Seeded likes and comments are demo activity, not testimonials.</p>}<div className="my-5 flex items-center gap-4"><Button variant={data.liked?'default':'outline'} disabled={busy||!user} onClick={()=>action(()=>axios.put(`${base}/social/${courseId}/like`,{liked:!data.liked},{withCredentials:true}))}><Heart size={16}/>{data.liked?'Liked':'Like'} · {data.likeCount}</Button><span className="text-sm text-muted-foreground">{data.commentCount} comments</span></div>{user?<form onSubmit={e=>{e.preventDefault();action(async()=>{await axios.post(`${base}/social/${courseId}/comments`,{text},{withCredentials:true});setText('');});}}><label htmlFor="course-comment" className="text-sm font-medium">Join the discussion</label><textarea id="course-comment" maxLength={1000} required value={text} onChange={e=>setText(e.target.value)} placeholder="Ask a question or share a learning tip" className="mt-2 min-h-24 w-full rounded-lg border bg-background p-3"/><div className="mt-2 flex justify-between"><span className="text-xs text-muted-foreground">{text.length}/1000</span><Button disabled={busy||!text.trim()} type="submit">Post comment</Button></div></form>:<p className="text-sm text-muted-foreground">Log in to like or comment.</p>}<div className="mt-6 space-y-4">{data.comments.length?data.comments.map(c=><article key={c._id} className="rounded-xl bg-muted/40 p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{c.user?.name||'Learner'}{(c.isDemo||c.user?.isDemo)&&<span className="ml-2 text-xs text-amber-700 dark:text-amber-300">Demo</span>}</p>{c.user?._id===user?._id&&<Button aria-label="Delete your comment" size="icon" variant="ghost" disabled={busy} onClick={()=>action(()=>axios.delete(`${base}/comments/${c._id}`,{withCredentials:true}))}><Trash2 size={16}/></Button>}</div><p className="mt-2 whitespace-pre-wrap break-words text-sm text-muted-foreground">{c.text}</p></article>):<p className="text-sm text-muted-foreground">No comments yet. Start the conversation.</p>}</div></>}</section>;
}
